# Generated by Django 3.1.7 on 2021-04-13 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('author', models.CharField(max_length=64, null=True)),
                ('cover_url', models.CharField(max_length=64, null=True)),
                ('publisher', models.CharField(max_length=64, null=True)),
                ('published_date', models.CharField(max_length=64, null=True)),
                ('subjects', models.TextField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('most_recent_added_dt', models.DateTimeField(auto_now=True)),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
