# Generated by Django 3.1.1 on 2021-04-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20210404_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
