# Generated by Django 3.1.1 on 2021-04-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20210404_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
